name: flutter_find_funny
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_easyloading: ^1.1.4
  awsome_video_player: ^1.0.8+1
  wechat_assets_picker: ^4.1.0+2
  tab_indicator_styler: ^1.0.0
  extended_list: ^2.0.1
  extended_image: ^1.1.0
  extended_sliver: ^1.0.1
  extended_nested_scroll_view: ^1.0.1 # sliver
  dio: ^3.0.10
  dio_cookie_manager: ^1.0.0
  event_bus: ^1.1.1
  shared_preferences: ^0.5.8
  provider: ^4.3.2+1
  flutter_swiper: ^1.1.6
  flutter_screenutil: ^2.3.1
  flutter_easyrefresh: ^2.1.5
  amap_location_fluttify: ^0.14.0+1
  permission_handler: ^5.0.1+1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  ff_annotation_route: ^3.4.0
  intl: ^0.16.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
