// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
const List<String> routeNames = <String>[
  'funny://find-list-page',
  'funny://movie-list-page',
  'funny://news-list-page',
  'funny://tabs-page',
  'funny://video-list-page',
];

class Routes {
  const Routes._();

  /// '发现页'
  ///
  /// [name] : 'funny://find-list-page'
  ///
  /// [routeName] : '发现页'
  static const String funnyFindListPage = 'funny://find-list-page';

  /// '影视页'
  ///
  /// [name] : 'funny://movie-list-page'
  ///
  /// [routeName] : '影视页'
  static const String funnyMovieListPage = 'funny://movie-list-page';

  /// '新闻页'
  ///
  /// [name] : 'funny://news-list-page'
  ///
  /// [routeName] : '新闻页'
  static const String funnyNewsListPage = 'funny://news-list-page';

  /// '底部导航页'
  ///
  /// [name] : 'funny://tabs-page'
  ///
  /// [routeName] : '底部导航页'
  static const String funnyTabsPage = 'funny://tabs-page';

  /// '搞笑视频页'
  ///
  /// [name] : 'funny://video-list-page'
  ///
  /// [routeName] : '搞笑视频页'
  static const String funnyVideoListPage = 'funny://video-list-page';
}
